version: '3'

services:

  postgres:
    build: ./compose/postgres
    env_file: .env

  redis:
    build: ./compose/redis
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file: .env

  nginx:
    build: ./compose/nginx
